/* HomeRanger — listings ingested from estate-agent emails, AI-extracted +
   scored against your taste. Prices are plain pounds for display.
   `ageHours` is a numeric sort key behind the human "lastSeen" label. */
const LISTINGS = [
  {
    id: "01HZ7A",
    address: "Reverdy Road, Bermondsey",
    outcode: "SE16", postcode: "SE16 4DG",
    price: 625000, bedrooms: 3, bathrooms: 2,
    propertyType: "Terraced", tenure: "Freehold", epc: "c",
    status: "pre_market", listingUrl: null, agency: "Field & Sons",
    photoCount: 9, score: 88, lastSeen: "2h ago", ageHours: 2,
    note: "Period terrace with bright, plant-filled rooms and a south-west garden two minutes from Southwark Park.",
  },
  {
    id: "01HZ7C",
    address: "Maynard Road, Walthamstow",
    outcode: "E17", postcode: "E17 9JE",
    price: 710000, bedrooms: 4, bathrooms: 2,
    propertyType: "Semi-detached", tenure: "Freehold", epc: "d",
    status: "pre_market", listingUrl: null, agency: "Stow Brothers",
    photoCount: 14, score: 81, lastSeen: "3h ago", ageHours: 3,
    note: "Generous family house near Lloyd Park. EPC D means some draughty sash windows to budget for.",
  },
  {
    id: "01HZ7F",
    address: "Fillebrook Road, Leytonstone",
    outcode: "E11", postcode: "E11 4AT",
    price: 660000, bedrooms: 3, bathrooms: 1,
    propertyType: "Terraced", tenure: "Freehold", epc: "c",
    status: "pre_market", listingUrl: null, agency: "Trading Places",
    photoCount: 0, score: null, lastSeen: "4h ago", ageHours: 4,
    note: "Arrived as text only — awaiting photos before it can be scored.",
  },
  {
    id: "01HZ7B",
    address: "Lynton Road, Bermondsey",
    outcode: "SE1", postcode: "SE1 5LB",
    price: 540000, bedrooms: 2, bathrooms: 1,
    propertyType: "Flat", tenure: "Leasehold", epc: "b",
    status: "live", listingUrl: "https://www.rightmove.co.uk/properties/example-lynton",
    agency: "Pedder", photoCount: 12, score: 74, lastSeen: "5h ago", ageHours: 5,
    note: "Modern conversion with a riverside walk nearby. Smaller than your ideal, no outdoor space beyond a Juliet balcony.",
  },
  {
    id: "01HZ7K",
    address: "Tressillian Road, Brockley",
    outcode: "SE4", postcode: "SE4 1XY",
    price: 689000, bedrooms: 3, bathrooms: 2,
    propertyType: "Terraced", tenure: "Freehold", epc: "c",
    status: "live", listingUrl: "https://www.zoopla.co.uk/example-tressillian",
    agency: "Brickworks", photoCount: 13, score: 79, lastSeen: "9h ago", ageHours: 9,
    note: "Wide Victorian terrace on a leafy street, the loft already converted. Kitchen is dated but sound.",
  },
  {
    id: "01HZ7D",
    address: "Choumert Road, Peckham",
    outcode: "SE15", postcode: "SE15 4SE",
    price: 585000, bedrooms: 2, bathrooms: 1,
    propertyType: "Maisonette", tenure: "Share of freehold", epc: "c",
    status: "live", listingUrl: "https://www.onthemarket.com/example-choumert",
    agency: "Aspire", photoCount: 8, score: 69, lastSeen: "1d ago", ageHours: 26,
    note: "Split-level maisonette with a roof terrace by Rye Lane. Compact second bedroom and a busy street below.",
  },
  {
    id: "01HZ7G",
    address: "Auckland Road, Crystal Palace",
    outcode: "SE19", postcode: "SE19 2RA",
    price: 775000, bedrooms: 4, bathrooms: 2,
    propertyType: "Semi-detached", tenure: "Freehold", epc: "d",
    status: "live", listingUrl: "https://www.rightmove.co.uk/properties/example-auckland",
    agency: "Paul Simon", photoCount: 16, score: 77, lastSeen: "2d ago", ageHours: 49,
    note: "Big Victorian semi with park views and a south garden. Top of budget and a longer commute than your usual outcodes.",
  },
  {
    id: "01HZ7M",
    address: "Ondine Road, East Dulwich",
    outcode: "SE15", postcode: "SE15 4EB",
    price: 720000, bedrooms: 4, bathrooms: 2,
    propertyType: "Terraced", tenure: "Freehold", epc: "d",
    status: "under_offer", listingUrl: "https://www.zoopla.co.uk/example-ondine",
    agency: "Roy Brooks", photoCount: 11, score: 72, lastSeen: "2d ago", ageHours: 54,
    note: "Handsome bay-fronted terrace near North Cross Road. Already under offer — kept for reference.",
  },
  {
    id: "01HZ7E",
    address: "Albyn Road, Deptford",
    outcode: "SE8", postcode: "SE8 4ED",
    price: 499000, bedrooms: 2, bathrooms: 1,
    propertyType: "Terraced", tenure: "Freehold", epc: "e",
    status: "under_offer", listingUrl: "https://www.onthemarket.com/example-albyn",
    agency: "Conran Estates", photoCount: 10, score: 63, lastSeen: "3d ago", ageHours: 74,
    note: "Cottage-style terrace in a conservation area. Under offer already, and the kitchen needs a full refit.",
  },
  {
    id: "01HZ7H",
    address: "Wilton Way, Hackney",
    outcode: "E8", postcode: "E8 1BG",
    price: 695000, bedrooms: 3, bathrooms: 2,
    propertyType: "Flat", tenure: "Leasehold", epc: "b",
    status: "withdrawn", listingUrl: "https://www.rightmove.co.uk/properties/example-wilton",
    agency: "Hunters", photoCount: 11, score: 71, lastSeen: "6d ago", ageHours: 146,
    note: "Warehouse-style flat on a much-loved street. Withdrawn from market last week.",
  },
];

window.LISTINGS = LISTINGS;
