apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: homeranger
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HzhaTYc7rs6fyAiWzB/h9fHI8VBRca0mUUOO/WnzguhIWsJN84tOzYjx8jx8CqcW8WqEu+Gjiqvgq7HAdX/76ozmt3oAHOp7Sa0fLf/o6C0l4tfB7EBNvmYYCE2TubcX4elSUgbX9h4yT8DRXdCDotNRjA47v5cO8Uxb3Da4KfqemBRc,iv:495WpVNs7FIjLF9S+O7OPU30/757QKJ7kn+Oq7+tBwc=,tag:mYIUqGYFrBjOxiMpNThwHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbGRMRGJFOUtwTU54b0Ny
            VWlkRUxRTUhVaVV1aVRXc0I3eDJLd3VDNVFNClVSUHRsYXpiOSt0VmNtWGxDcFdD
            dEhYczZRdkN0dTlPM1FVVFc2R2QybjAKLS0tIFowZENqNGNnOElDWlN0ZzlkNVpD
            aWY2UlJFUEdQQXVHN0ZDeWRQNVdKczgKVUivoLGJv2BOD7Z2mM53T/h3jW9SMTSR
            RsVE3vBsn3e7JRJ2tyiJif6hwn2AvPbeMrOxuW0OVp7LuMZJSqStHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sklvl49hxvrhn4wmjceuyf7f9qplnglks3naeeckgjkp3y04xduqzht27a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T09:48:50Z"
    mac: ENC[AES256_GCM,data:9sEk7HjwbqeG77erTqW/i4l7x12nKEkPwZHGE8imHAVnVaaiWYDmGI0o1oM6Ef1Nl7xkuCAyw2Txt3XZbNkB1YHWA8hHUgaUTYEZ/Q4YdDL4vEMuHEiccFyF7rx3VwOkpKY9IQb4FNaWuc+CeG2/131jKRc1iBfg6YVjRscX4Rc=,iv:kqF+oYwOPovdLh/YF6sTPdaeLoRJh1knkGEwBG11EWU=,tag:l+2nN3fG6VmAl0IxhwKExQ==,type:str]
    version: 3.13.1
