apiVersion: v1
kind: Secret
metadata:
    name: homescout-secret
    namespace: homescout
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:38ydA6hcB6YrA+ctmJ+G,iv:wYdUOzBhiN8INEZjl5eor6Q6VEJ3AXAZP57lN7TWapY=,tag:WkUAuFTiEwtziyAgbGGqrA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nDMm7ZJUckvIfGEGzMbO+FpuldxNR0kJHj+0Fs1VoBCCpXFOYqASG8V1a/01TMU0,iv:zcPMyTJpYhzJ2m6nCFhvbJOsmC1cWq52/6jmhWv+Aow=,tag:wo1v2p184iFWOmGgQX26EQ==,type:str]
    HOMESCOUT_APP_PASSWORD: ENC[AES256_GCM,data:j4przBR/sL1zVfqXArSPxUV7/fGj+S/h35kHs17xZKefQ/6ikf7JCotOmxDq+64Z,iv:8cpEFDucueSF9Tu+Vn9euROPxX0E6H0ZUraeFnCYDs0=,tag:TpvE14oAvnrS/Ag0OoxQAw==,type:str]
    HOMESCOUT_MIGRATOR_PASSWORD: ENC[AES256_GCM,data:Nj4fftvtMrrtOIsC5stW9XaawoQpJ7Cn/mBnb/rudoXzGX0jp1DaZt6oSXw3Hd6e,iv:hDSp3W2SUPpPwAmY3HpC9wY82gkufy1woUuLf6nAkcA=,tag:UN6A+dzsSn2xA+sMsubbKA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:hIqUq/gaYiGwIYcU3I3hs11SntGCoX4blgJe4ZGNIXVqCJJjTENusZdKvadOORFY9ibFGB/EeK9g+4ew6CfdORNQ1bOCgmpz+iV6CRWvJjVpvDmTL4313TRyHjq9DqIMPBXhNL0VektWbHmmy4B6BKVr2y1F5e3BqfB8iAM7zWeCYDwb3PNEhAC/zmHQiw+kUOzg,iv:w/uC+v3mOaVBV2lIxStYlZsIvLB/wSySpb8U6s55WtQ=,tag:FpMwEx69Tzzuh0uT/ZFi3g==,type:str]
    MIGRATION_DATABASE_URL: ENC[AES256_GCM,data:V4IRvqOA+dtMbOxWMg8U0I7TNc2fyK7w3/sLyf01i656+duCxd4I/Q5OIZM67lJvY+OWmnliK1nAoW+DffDejBV97Rzd/YU7EOKg1H6978rtRVxfs/tXz83GGcu1NbrQxSxwwosYYkzmQbqG5SLFBsbAstjL1KotK/HAyj/q+R+XulJuNS1K0LeqRh3R23vOHiL1j5UV3QWBjEyT,iv:zDDUge13Dlh6bj+6dECIu396xcMfWkL0mWbEBpiA/74=,tag:v+tD65/+WMpuLHuYwdbj6Q==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:mooZVzqyLPFnCdUwEGwrRgyPOn2rRSWFrJ1b4ILc9MyFZ2DJ7GaxIp7j7YMSz1/G,iv:f64PwyOJe/Ox/w9fpUpovSi3/3TSPFHli8GoyvRkDhM=,tag:Q5fZmuJQdrBCPUitFh70uw==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:NonSItvfx/HjHb0I1voLrZEDTQAQadl+uiG1+GojDQm9OQ6P0I/tM2aaE5epDqL7AzwvsrvixuQR6ehrlAL+xrRDBuL0vk88aBtpxk+aQrHbeBbyeya4NZRPIZS1mHeJxQxlBkmUSzUd14or,iv:n/l9s3qVu5J4J8IZYbVKtwQbdt7AL2iodcng5oOda/w=,tag:jHHapbL/ehDI0pN5IeBRRg==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:VC5MgZh0++nfoZeNNlq8G3nSErdXEuOW4ZT4rJHg7lMeA0pXAKKAalpThYMBOw==,iv:o835oByNTsv3HXRx/sEF19IbwZSAGguf6bgmw2sSu74=,tag:y4mexX3eq4MpIj3hls1gNg==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:7uScdK4P4WEKoAc8L7Q5KJpBuBnfUl29G94pgv2cDaJTO23A,iv:niLRZSqu7og9TzWKQ2EbY2ExlbgAojzHOUlCwGQtpps=,tag:S4o6xiZfA7l4YBB2wY3PvQ==,type:str]
    RESEND_INBOUND_WEBHOOK_SECRET: ENC[AES256_GCM,data:S439E1hnbUDRzlmJVuwkq/WoMJY8Obs6RUws8OgrRSIL2vHlMbkA/FUfULD6B0lP,iv:pPrwuMR/l6k6XXdjw6ePc2TRhoVnqxRXxKlTvgDNFZw=,tag:skZuLu9WpUxs8qGQWBpFYQ==,type:str]
    RESEND_WEBHOOK_SECRET: ENC[AES256_GCM,data:yiSykl8dJQOXPu3Gx17JbFrcQK8lxtVfs/INig5aqPLsfq7o6/X1UUWc1sTEanyK,iv:z4+KWcoeFz7St6XB33UQ+Fw4bE1Ad8w6kJYNIY6FepI=,tag:CecFmwAKEZuwtliLFisP9Q==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:V4brw6i5JmQ7ZQD6PwLbKFxxBTziF125NSbjdtyx6Ug=,iv:FjNqPRQ6RL8y8+6AB2ltO8mT0zi6fm99fv+v1TZwK+A=,tag:9bS9IhM9sY8ya8a/mTnX7g==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lMx9L1oUHvssD6re4zjt7n1qywXM3TQnUKaL8CkM8CdtmjO7Xn5hocs1dh8VlkHmmhXd2/jgLCK+QKZELWd7ow==,iv:QBeg5ObqpgXhQcQ3/5rP0Cv3MNVVdeDhQNkUDll3XgE=,tag:dVhLlMTLknpZ63Hto47mHg==,type:str]
    R2_BUCKET: ENC[AES256_GCM,data:g99MrnBijyrqvMuq+cmsNhWHBNKV,iv:Dv6p7SE1WJX9PXoPiDPGNdsJcZWBWSyHCqbVWlETsRE=,tag:6Esu2jx5E2ZGfr9qIshJdg==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:qLsxiS2gkmcXTSV4hVkmFP0+iXVgyWSMrkaLV/DVv0HjvWaLhR3IfbGi1zc1wIFPIekUfDhe824NyCB1QgZ6tr18gno=,iv:5By4cLyIbHJzrBNeONux83XHhYs3yIKvi9TNz9xHmK0=,tag:DpDeSuwobvytomMhrYGzfg==,type:str]
    CF_AI_GATEWAY_ACCOUNT_ID: ENC[AES256_GCM,data:PX6k8XFE/Kpi7APa1Qs5bRUCkuHC3MheCb82NKBzaA4=,iv:3/zhoLJZSY0KOx+eQl+y30bQArLuekoU+ATp23i1aMw=,tag:57AbIYzmb5iaz33HzdjFlQ==,type:str]
    CF_AI_GATEWAY_ID: ENC[AES256_GCM,data:Z/j39/XFwfRA,iv:2dTyGuu0bnQ3uL1ipJA38PEa7L3mk+xsOCfWqhQldaw=,tag:00k7wQAr+NmPfsLyiqN86w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aEY3VXpmRFQ4T0IxT3lD
            UGRzMTJtdVhYSU55NCtYYXJoU1hwSy9zM21nCnB0RE9hWkVLZkN6STlZdERISXk4
            a0JYN1dLZjJhNmVMcVlpZG1laEg1aUkKLS0tIGtWRXlGZ0RsUmZ3M0JjTVNmUG00
            NFF5U3QvR1NBOGxaWXZ1eXFISVRiSUkKTab6BNRwCcd0XrHKUTnGcnaFCmkkaXuc
            iBMHdD1BkKu6l4S0ut4THSIscqWkW0tcuFCuvBf9g4HJBK5U5BecQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sklvl49hxvrhn4wmjceuyf7f9qplnglks3naeeckgjkp3y04xduqzht27a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T10:12:11Z"
    mac: ENC[AES256_GCM,data:/I/e0c1+F6IenHOBrWLV772Q0SAtot2tajT1AeEfdRypp5Uorio5r6mIrmVSbC7kQkJsHHwnxbi1ezmCgJMIV4NuguU1nHC5JFmt8RzjGxek4L/gRwbjhD0Kr1UdFDJwaaU3yPvlei9gSwhzERYLNMC8G9jvved5SVnWsRUi7Dk=,iv:xwHtzRvE9e4RjRDi97+LYZWoi6Qj4zuBO4oGE2xbuhA=,tag:fyTCc/OlDk9GTyn2nkrcdg==,type:str]
    version: 3.13.1
